import { Router } from "express";
import { AuthRoutes } from "../module/auth/auth.router";
import { CategoryRoutes } from "../module/category/category.route";
import { ShopRoutes } from "../module/shop/shop.route";
import { ProductRoutes } from "../module/product/product.route";
import { CartRoutes } from "../module/cart/cart.route";
import { OrderRoutes } from "../module/order/order.route";
import { ReviewRoutes } from "../module/review/review.route";
import { AnalyticsRoutes } from "../module/analytics/analytics.route";
import { RagRoutes } from "../module/rag/rag.route";
import { AdminRoutes } from "../module/admin/admin.route";
import { AIRoutes } from "../module/ai/ai.route";
import { AttributeRoutes } from "../module/attribute/attribute.route";
import { CouponRoutes } from "../module/coupon/coupon.route";
import { ShippingSettingRoutes } from "../module/shipping-setting/shippingSetting.route";
import { HeroSliderRoutes } from "../module/hero-slider/heroSlider.route";
import { PosRoutes } from "../module/pos/pos.route";
import { SiteSettingRoutes } from "../module/site-setting/siteSetting.route";
import { LandingPageRoutes } from "../module/landing-page/landingPage.route";

const router = Router();

router.use("/auth", AuthRoutes);
router.use("/admin", AdminRoutes);
router.use("/categories", CategoryRoutes);
router.use("/shops", ShopRoutes);
router.use("/products", ProductRoutes);
router.use("/cart", CartRoutes);
router.use("/orders", OrderRoutes);
router.use("/reviews", ReviewRoutes);
router.use("/analytics", AnalyticsRoutes);
router.use("/rag", RagRoutes);
router.use("/ai", AIRoutes);
router.use("/attributes", AttributeRoutes);
router.use("/coupons", CouponRoutes);
router.use("/shipping-settings", ShippingSettingRoutes);
router.use("/hero-sliders", HeroSliderRoutes);
router.use("/pos", PosRoutes);
router.use("/site-settings", SiteSettingRoutes);
router.use("/landing-pages", LandingPageRoutes);

export const IndexRoutes = router;
